version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: traffic-backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d  # ← this allows seeding
    environment:
      MONGO_INITDB_DATABASE: traffic_db
    restart: always

volumes:
  mongo_data:
